# -*- coding: utf-8 -*-
"""Biblioteka_pandas_zadania_dla_studentów.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVybfXD7mMCgcxP5-WbVy8yINWGJSk_g
"""

import pandas as pd

date = {
    "name": ["Anna", "Jan", "Maria", "Tomasz", "Katarzyna"],
    "surname": ["Kowalska", "Nowak", "Wiśniewska", "Kaczmarek", "Zielińska"],
    "age": [28, 35, 42, 19, 30],
    "city": ["Warszawa", "Kraków", "Poznań", "Wrocław", "Gdańsk"],
    "income": [5000, 6200, 7100, 3200, 4600]
}

df = pd.DataFrame(date)
df.to_csv("date.csv", index=False)

"""### Wczytaj plik CSV o nazwie dane.csv i wyświetl pierwsze 5 wierszy."""



"""### Wyświetl podstawowe statystyki opisowe (średnia, mediana, min, max itd.) dla danych."""



"""### Wyświetl informacje o kolumnach i typach danych (np. za pomocą .info())."""



"""### Wyświetl wszystkie wiersze, w których wartość w kolumnie wiek jest większa niż 30."""



"""### Wyświetl wszystkie wiersze, w których wartość w kolumnie wiek jest większa niż 30."""



"""### Dodaj nową kolumnę rok_urodzenia, zakładając że obecny rok to 2025 i korzystając z kolumny wiek."""



"""### Oblicz średnią wartość kolumny dochód."""



"""### Zgrupuj dane po kolumnie miasto i policz średni wiek w każdej grupie."""



"""### Zapisz przetworzone dane do nowego pliku CSV o nazwie nowe_dane.csv."""



"""### Usuń wszystkie wiersze zawierające brakujące wartości (NaN)."""

