# -*- coding: utf-8 -*-
"""One-hot encoding - kodowanie kolumn cz.6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y6Pfm4NlIeoSgjH0TpwacmV9A4SNewB_

###One-hot encoding - kodowanie kolumn kategorycznych

###**Import bibliotek**
"""

import pandas as pd

df = pd.DataFrame({"x": list(range(100)),"y":["a", "b", "c", "d"]*25})

"""Przy pomocy biblioteki **one-hot encoding** będziemy chcieli zakodować kalumnę y."""

df.head()

"""Dla zmiennej y - zmiennej typu string utworzone zostały nowe kolumny.

Każda z tych kolumn ma taką nazwę jak nazwa pierwotnej kolumny prefiks nazwa kategorii, która tutaj występuje.

Wartościami tych zmiennych są 1 i 0.

"""

pd.get_dummies(df["y"], dtype='int').head()

