# -*- coding: utf-8 -*-
"""Tutorial - introduction cz.1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1njLvE0a77uHyHbBz4KMJRrHrAmgAKlVs
"""

from google.colab import drive
drive.mount('/content/drive')

!pwd

!ls /content/drive

"""### **Kopiowanie repozytorium git**"""

!git clone url

"""###**Instalowanie bibliotek Pythona**"""

!pip

"""###**Sprawdzamy jakie biblioteki są już zainstalowane**"""

!pip freeze

